/**
 * Envelope encryption for broker API credentials — the Deno half of the contract.
 *
 * This MUST stay byte-compatible with `api/src/engine/crypto.py`: the edge
 * function writes credentials and the Python engine reads them. The format is
 * specified in that module's docstring and enforced by
 * `api/tests/test_crypto_interop.py`, which runs both runtimes against each
 * other in CI rather than trusting a copied-in test vector.
 *
 *     v<keyVersion>.<base64url(iv)>.<base64url(ciphertext || tag)>
 *
 * WebCrypto's AES-GCM appends the 16-byte tag to the ciphertext, which is what
 * Python's AESGCM also produces, so neither side splices buffers.
 */

const IV_BYTES = 12; // 96-bit nonce, the size GCM is specified for
const KEY_BYTES = 32; // AES-256
const TAG_BITS = 128;

export class CryptoError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "CryptoError";
  }
}

function b64urlEncode(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function b64Decode(text: string): Uint8Array {
  // Accept both alphabets so a key generated by any tool works, and restore the
  // padding that b64urlEncode strips.
  const normalised = text.replace(/-/g, "+").replace(/_/g, "/");
  const padded = normalised + "=".repeat((4 - (normalised.length % 4)) % 4);
  const binary = atob(padded);
  return Uint8Array.from(binary, (c) => c.charCodeAt(0));
}

async function importKey(encodedKey: string): Promise<CryptoKey> {
  let raw: Uint8Array;
  try {
    raw = b64Decode(encodedKey);
  } catch {
    throw new CryptoError("APP_ENCRYPTION_KEY is not valid base64");
  }
  if (raw.length !== KEY_BYTES) {
    throw new CryptoError(
      `APP_ENCRYPTION_KEY must decode to ${KEY_BYTES} bytes, got ${raw.length}`,
    );
  }
  return await crypto.subtle.importKey("raw", raw, { name: "AES-GCM" }, false, [
    "encrypt",
    "decrypt",
  ]);
}

export interface CryptoOptions {
  /** base64 of 32 bytes, from APP_ENCRYPTION_KEY. */
  key: string;
  /** The owning user id, bound in as additional authenticated data. */
  aad: string;
  keyVersion?: number;
}

export async function encryptSecret(
  plaintext: string,
  { key, aad, keyVersion = 1 }: CryptoOptions,
): Promise<string> {
  if (!plaintext) throw new CryptoError("refusing to encrypt an empty value");

  const cryptoKey = await importKey(key);
  // A fresh IV per call. Reusing one under the same key is the single fastest
  // way to break GCM outright.
  const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES));

  const sealed = new Uint8Array(
    await crypto.subtle.encrypt(
      {
        name: "AES-GCM",
        iv,
        additionalData: new TextEncoder().encode(aad),
        tagLength: TAG_BITS,
      },
      cryptoKey,
      new TextEncoder().encode(plaintext),
    ),
  );

  return `v${keyVersion}.${b64urlEncode(iv)}.${b64urlEncode(sealed)}`;
}

export async function decryptSecret(
  envelope: string,
  { key, aad }: CryptoOptions,
): Promise<string> {
  const parts = envelope.split(".");
  if (parts.length !== 3) throw new CryptoError("malformed credential envelope");

  const [version, ivPart, payloadPart] = parts;
  if (!/^v\d+$/.test(version)) {
    throw new CryptoError(`unsupported credential envelope version: ${version}`);
  }

  let iv: Uint8Array;
  let sealed: Uint8Array;
  try {
    iv = b64Decode(ivPart);
    sealed = b64Decode(payloadPart);
  } catch {
    throw new CryptoError("credential envelope is not valid base64url");
  }
  if (iv.length !== IV_BYTES) {
    throw new CryptoError(`expected a ${IV_BYTES}-byte iv, got ${iv.length}`);
  }

  try {
    const opened = await crypto.subtle.decrypt(
      {
        name: "AES-GCM",
        iv,
        additionalData: new TextEncoder().encode(aad),
        tagLength: TAG_BITS,
      },
      await importKey(key),
      sealed,
    );
    return new TextDecoder().decode(opened);
  } catch {
    // Deliberately uniform: telling a caller whether the key was wrong, the
    // user was wrong, or the bytes were tampered with tells an attacker which
    // of the three they achieved.
    throw new CryptoError("credential could not be decrypted");
  }
}

/** Last 4 characters, for the UI to show which key is attached. */
export function hintOf(secret: string): string {
  return secret.length >= 4 ? secret.slice(-4) : "****";
}
