"""Envelope encryption for broker API credentials.

The assignment requires API keys to be encrypted before storage and never
returned to the browser. Two independent runtimes touch these bytes -- the Deno
edge function writes them, this engine reads them -- so the envelope format is a
contract, not an implementation detail. It is specified here and mirrored in
``supabase/functions/_shared/crypto.ts``; ``tests/test_crypto.py`` pins the
format with vectors that the Deno side must also satisfy.

Envelope
--------
    v<key_version>.<base64url(iv)>.<base64url(ciphertext || tag)>

* AES-256-GCM. 96-bit random IV per encryption, never reused.
* The 16-byte GCM tag is appended to the ciphertext, which is what both
  ``cryptography``'s AESGCM and WebCrypto's ``AES-GCM`` do natively, so neither
  side needs to splice buffers.
* The owning ``user_id`` is bound in as additional authenticated data. A row
  lifted from one user and pasted onto another fails authentication instead of
  decrypting -- the ciphertext is only valid *where it was written*.
"""

from __future__ import annotations

import base64
import hashlib
import os

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

KEY_BYTES = 32  # AES-256
IV_BYTES = 12  # 96-bit nonce, the GCM-recommended size


class CryptoError(Exception):
    """Key material or ciphertext that cannot be used."""


def _b64url_encode(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def _b64url_decode(text: str) -> bytes:
    padding = "=" * (-len(text) % 4)
    return base64.urlsafe_b64decode(text + padding)


def load_key(encoded: str) -> bytes:
    """Decode and validate the master key from its base64 env representation."""
    if not encoded:
        raise CryptoError("APP_ENCRYPTION_KEY is not set")
    try:
        # Accept both standard and url-safe base64 so a key generated by any
        # tool works; operators should not have to care which alphabet was used.
        key = base64.b64decode(encoded, validate=False)
    except Exception as exc:  # noqa: BLE001 - any decode failure is the same error
        raise CryptoError("APP_ENCRYPTION_KEY is not valid base64") from exc
    if len(key) != KEY_BYTES:
        raise CryptoError(
            f"APP_ENCRYPTION_KEY must decode to {KEY_BYTES} bytes, got {len(key)}"
        )
    return key


def generate_key() -> str:
    """A fresh base64 master key, for ``scripts/gen-keys.sh``."""
    return base64.b64encode(os.urandom(KEY_BYTES)).decode("ascii")


def encrypt(plaintext: str, *, key: bytes, aad: str, key_version: int = 1) -> str:
    """Encrypt ``plaintext``, binding it to ``aad`` (the owning user id)."""
    if not plaintext:
        raise CryptoError("refusing to encrypt an empty value")
    iv = os.urandom(IV_BYTES)
    sealed = AESGCM(key).encrypt(iv, plaintext.encode("utf-8"), aad.encode("utf-8"))
    return f"v{key_version}.{_b64url_encode(iv)}.{_b64url_encode(sealed)}"


def decrypt(envelope: str, *, key: bytes, aad: str) -> str:
    """Reverse :func:`encrypt`.

    Raises :class:`CryptoError` on a wrong key, a tampered payload, or an
    ``aad`` that does not match the one used at encryption time.
    """
    try:
        version, iv_part, payload_part = envelope.split(".", 2)
    except ValueError as exc:
        raise CryptoError("malformed credential envelope") from exc

    if not version.startswith("v") or not version[1:].isdigit():
        raise CryptoError(f"unsupported credential envelope version: {version!r}")

    try:
        iv = _b64url_decode(iv_part)
        sealed = _b64url_decode(payload_part)
    except Exception as exc:  # noqa: BLE001
        raise CryptoError("credential envelope is not valid base64url") from exc

    if len(iv) != IV_BYTES:
        raise CryptoError(f"expected a {IV_BYTES}-byte iv, got {len(iv)}")

    try:
        opened = AESGCM(key).decrypt(iv, sealed, aad.encode("utf-8"))
    except InvalidTag as exc:
        # Deliberately vague: distinguishing "wrong key" from "wrong user" from
        # "tampered" would tell an attacker which of the three they achieved.
        raise CryptoError("credential could not be decrypted") from exc
    return opened.decode("utf-8")


def key_version_of(envelope: str) -> int:
    """Read the key version without needing the key -- used by rotation tooling."""
    head = envelope.split(".", 1)[0]
    if not head.startswith("v") or not head[1:].isdigit():
        raise CryptoError(f"unsupported credential envelope version: {head!r}")
    return int(head[1:])


def hint_of(secret: str) -> str:
    """The last 4 characters of a key, for the UI to show which key is attached."""
    return secret[-4:] if len(secret) >= 4 else "****"


def fingerprint(secret: str) -> str:
    """A stable, non-reversible id for a credential, safe to log."""
    return hashlib.sha256(secret.encode("utf-8")).hexdigest()[:12]
